spring:
  application:
    name: "identity-service"
  datasource:
    url: "jdbc:postgresql://localhost:5434/identity-service"
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddlAuto: update


server:
  port: 8083