spring:
  application:
    name: "order-service"
  datasource:
    url: "jdbc:postgresql://localhost:5433/order-service"
    username: admin
    password: test

  cloud:
    stream:
      function:
        definition: orderCreatedFunction
      bindings:
        orderCreatedFunction-out-0:
          destination: order-topic
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddlAuto: update
server:
  port: 8085